### ISSUE TITLE
VCN Argument is deprecated

### ISSUE THREAD

**Issue by jorgeceballosgarcia** [oracle-quickstart/oke-soa#1]
Warning: Argument is deprecated
│
│   with module.vcn.oci_core_route_table.public_rt,
│   on modules/vcn/main.tf line 29, in resource "oci_core_route_table" "public_rt":
│   29: resource "oci_core_route_table" "public_rt" {
│
│ The 'cidr_block' field has been deprecated. Please use 'destination' instead.

**Comment by streamnsight** [comment]
fixed in new release
