### ISSUE TITLE
Unable to deploy OKE SOA K8S cluster - timeout on the nodepool creation

### ISSUE THREAD

**Issue by enduro99kb** [oracle-quickstart/oke-soa#8]
Hello,
I'm trying to deploy the SOA Quickstart on OKE, but I'm getting below error:

```
Error:

│ Error: Work Request error
│ Provider version: 4.82.0, released on 2022-06-29. This provider is 4 Update(s) behind to current.
│ Service: Containerengine Node Pool
│ Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.eu-frankfurt-1.aaaaaaaa544iifbjj334zgkjfpqgwjl2e3sxtc63c5jtvcw4kwpqcunj3ssa, entity: nodepool, action: CREATED. Message: 3 nodes(s) register timeout
│ Resource OCID: ocid1.nodepool.oc1.eu-frankfurt-1.aaaaaaaavzlihxjzpyvtt5palyfr3btraqkbwh6kzzymyh47vnamwdkh46sa
│ Suggestion: Please retry or contact support for help with service: Containerengine Node Pool
│
│
│   with module.node_pools.oci_containerengine_node_pool.node_pool[0],
│   on modules/node_pool/main.tf line 4, in resource "oci_containerengine_node_pool" "node_pool":
│    4: resource "oci_containerengine_node_pool" "node_pool" {
│

```

Full "terraform apply" output:

 
[Terraform_apply_NodePool_creation_timeout_20220801.txt](https://github.com/oracle-quickstart/oke-soa/files/9234350/Terraform_apply_NodePool_creation_timeout_20220801.txt)

Thank you in advance for help.

Regards,
Piotr Michalski
Oracle ACS

**Comment by streamnsight** [comment]
typically, you'd see error messages on the node pool job request area in the OCI console. Check there, and most likely there it is a node shape availability/quota issue.

**Comment by enduro99kb** [comment]
Hello,
thank you for the hint. I'm repeating the attempt to create the OKE cluster with different vcn_cidr. 
Regards,
Piotr

**Comment by enduro99kb** [comment]
Hello,
I'm closing this issue. Issue fixed after OCI administrators allocated more quota to the compartment. Thank you for your help.
Regards,
Piotr
